# This is a basic workflow to help you get started with Actions

name: Automation of website

# Controls when the workflow will run
on:
  workflow_dispatch:  
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Install Python,pip and pelican
        run: |
          sudo apt-get install python3.11-full
          sudo apt install python3-pip
          python3 -m pip install "pelican[markdown]"
          pelican content
          cd /home/runner/work/projects/projects/output
          ls -al
          cat index.html 
      - name: Upload the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: /home/runner/work/projects/projects/output/*

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
  deploy:
    needs: build
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:

    - name: Create a directoty to download artefacts
      run: mkdir -p /upload
    - name: Download the artifacts
      uses: actions/download-artifact@v3
      with:
        name: website
        path: /upload
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::627517169336:role/Github
        aws-region: us-west-2
    - name: Listing files that will be uploaded
      run: |
        ls -lah /upload/
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync /upload/ s3://www.katkarviraj.com
#        aws s3 sync /home/runner/work/projects/projects/output/ s3://www.katkarviraj.com
    - name: Invalidate cloudfront
      run: aws cloudfront create-invalidation --distribution-id E3H5FWYDB7EZXV --paths "/*"
        
#      uses: chetan/invalidate-cloudfront-action@v2
#     env:
#          DISTRIBUTION: ${{ env.CF_DISTRIBUTION }}
 #         PATHS: "/*"
  #        AWS_REGION: "us-west-2"
                    
      
